[package]
name = "memo"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "*"
serde = { version = "*", features = ["derive"] }
serde_cbor = "*"
postcard = { version = "*", features = ["use-std"] }
clipboard = "0.5.0"

[features]
default = []
postcard = []
